name = "my-remix-portpoilo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "build/client"

[vars]
OWNER_NAME = "홍훈의"
OWNER_POSITION = "임베디드 SW 개발자"

[[d1_databases]]
binding = "DB"
database_name = "huneui_hong_portfolio_db"
database_id = "9fd2990b-2df4-40a1-9b20-3e0f71f2014f"

